"""Verified public SmartRecruiters employer boards used for cross-sector coverage.

Each identifier is a public employer career-site identifier, not a scraped page.
The registry is deliberately curated so source reporting can name exactly which
employers were queried and why they were eligible for a search.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SmartRecruitersSource:
    identifier: str
    organization: str
    query_terms: frozenset[str]
    role_families: frozenset[str] = frozenset()
    industries: frozenset[str] = frozenset()
    location_terms: frozenset[str] = frozenset()
    fallback_priority: int = 0


def _source(
    identifier: str,
    organization: str,
    query_terms: set[str],
    *,
    role_families: set[str] | None = None,
    industries: set[str] | None = None,
    location_terms: set[str] | None = None,
    fallback_priority: int = 0,
) -> SmartRecruitersSource:
    return SmartRecruitersSource(
        identifier=identifier,
        organization=organization,
        query_terms=frozenset(query_terms),
        role_families=frozenset(role_families or set()),
        industries=frozenset(industries or set()),
        location_terms=frozenset(location_terms or set()),
        fallback_priority=fallback_priority,
    )


PHILADELPHIA_LOCATION_TERMS = {
    "philadelphia",
    "philly",
    "pennsylvania",
    "pa",
    "king of prussia",
    "conshohocken",
    "malvern",
    "wayne",
    "radnor",
    "exton",
    "west chester",
    "newtown square",
    "fort washington",
    "horsham",
    "blue bell",
    "plymouth meeting",
    "audubon",
    "camden",
    "cherry hill",
    "mount laurel",
    "wilmington",
}


SMARTRECRUITERS_SOURCES: tuple[SmartRecruitersSource, ...] = (
    _source(
        "CityofPhiladelphia",
        "City of Philadelphia",
        {
            "government",
            "public service",
            "policy analyst",
            "policy",
            "social worker",
            "librarian",
            "library",
            "public health",
            "engineer",
            "engineering",
            "electrician",
            "plumber",
            "carpenter",
            "hvac",
            "mechanic",
            "operator",
            "accountant",
            "accounting",
            "administrative assistant",
            "legal assistant",
            "paralegal",
            "attorney",
            "city solicitor",
            "software engineer",
            "data analyst",
            "gis",
            "communications",
            "human resources",
            "recruiter",
        },
        role_families={
            "policy",
            "operations",
            "healthcare",
            "finance",
            "data",
            "software",
            "legal",
            "legal_operations",
            "contracts",
            "compliance",
            "marketing",
        },
        industries={"government", "public_interest", "public_policy", "legal_services"},
        location_terms=PHILADELPHIA_LOCATION_TERMS,
        fallback_priority=12,
    ),
    _source(
        "HealthFederationOfPhiladelphia",
        "Health Federation of Philadelphia",
        {
            "nurse",
            "nursing",
            "social worker",
            "community health worker",
            "public health",
            "health educator",
            "educator",
            "case manager",
            "care manager",
            "behavioral health",
            "counselor",
            "medical assistant",
            "administrative assistant",
            "program coordinator",
        },
        role_families={"healthcare", "operations", "policy"},
        industries={"healthcare", "nonprofit", "public_interest"},
        location_terms=PHILADELPHIA_LOCATION_TERMS,
        fallback_priority=10,
    ),
    _source(
        "KIPP",
        "KIPP",
        {
            "teacher",
            "teaching",
            "education",
            "educator",
            "school",
            "school counselor",
            "counselor",
            "social worker",
            "school psychologist",
            "speech language pathologist",
            "occupational therapist",
            "physical therapist",
            "paraprofessional",
            "school nurse",
            "librarian",
            "library",
            "instructional coach",
            "curriculum",
            "academic advisor",
            "administrative assistant",
            "operations",
            "human resources",
            "finance",
            "bus driver",
            "custodian",
        },
        role_families={"operations", "healthcare", "policy", "finance"},
        industries={"education", "nonprofit"},
        fallback_priority=10,
    ),
    _source(
        "AECOM2",
        "AECOM",
        {
            "civil engineer",
            "mechanical engineer",
            "electrical engineer",
            "environmental engineer",
            "structural engineer",
            "transportation engineer",
            "water resources engineer",
            "engineer",
            "engineering",
            "architect",
            "architecture",
            "urban planner",
            "planner",
            "geologist",
            "environmental scientist",
            "scientist",
            "gis",
            "construction",
            "project manager",
            "technician",
        },
        role_families={"operations", "data", "design", "finance"},
        industries={"engineering", "construction", "environmental_services", "government"},
        fallback_priority=11,
    ),
    _source(
        "CRB",
        "CRB",
        {
            "process engineer",
            "chemical engineer",
            "mechanical engineer",
            "electrical engineer",
            "biomedical engineer",
            "engineer",
            "engineering",
            "architect",
            "architecture",
            "construction",
            "project manager",
            "designer",
            "life science",
            "manufacturing",
            "new grad",
        },
        role_families={"operations", "design", "healthcare"},
        industries={"engineering", "construction", "life_sciences", "healthcare"},
        fallback_priority=10,
    ),
    _source(
        "BoschGroup",
        "Bosch Group",
        {
            "electrical engineer",
            "mechanical engineer",
            "industrial engineer",
            "manufacturing engineer",
            "engineer",
            "engineering",
            "technician",
            "machinist",
            "manufacturing",
            "quality",
            "supply chain",
            "maintenance",
        },
        role_families={"software", "data", "operations", "finance"},
        industries={"manufacturing", "engineering", "technology"},
        fallback_priority=10,
    ),
    _source(
        "Bosch-HomeComfort",
        "Bosch Home Comfort",
        {
            "hvac",
            "heating technician",
            "air conditioning technician",
            "field service technician",
            "service technician",
            "electrician",
            "plumbing",
            "mechanical engineer",
            "electrical engineer",
            "warehouse",
            "maintenance",
        },
        role_families={"operations", "marketing", "finance"},
        industries={"manufacturing", "engineering", "construction"},
        fallback_priority=8,
    ),
    _source(
        "VeoliaEnvironnementSA",
        "Veolia",
        {
            "environmental scientist",
            "environmental science",
            "civil engineer",
            "chemical engineer",
            "engineer",
            "engineering",
            "electrician",
            "plumber",
            "mechanic",
            "operator",
            "maintenance technician",
            "water",
            "wastewater",
            "utilities",
        },
        role_families={"operations", "data", "finance"},
        industries={"environmental_services", "government", "public_interest"},
        fallback_priority=8,
    ),
    _source(
        "Eurofins",
        "Eurofins",
        {
            "chemist",
            "chemistry",
            "biologist",
            "biology",
            "laboratory",
            "lab technician",
            "scientist",
            "research",
            "quality",
            "microbiology",
            "environmental science",
        },
        role_families={"data", "operations", "healthcare"},
        industries={"healthcare", "life_sciences"},
        fallback_priority=9,
    ),
    _source(
        "SGS",
        "SGS",
        {
            "laboratory",
            "lab technician",
            "chemist",
            "scientist",
            "inspection",
            "inspector",
            "quality",
            "environmental",
            "engineering",
            "technician",
        },
        role_families={"operations", "healthcare", "data"},
        industries={"life_sciences", "environmental_services"},
        fallback_priority=7,
    ),
    _source(
        "LGCGroup",
        "LGC Group",
        {
            "chemist",
            "chemistry",
            "biology",
            "genomics",
            "laboratory",
            "scientist",
            "research",
            "quality",
            "manufacturing",
        },
        role_families={"operations", "healthcare", "data"},
        industries={"healthcare", "life_sciences"},
        fallback_priority=6,
    ),
    _source(
        "USPhysicalTherapy2",
        "US Physical Therapy",
        {
            "physical therapist",
            "physical therapy",
            "physical therapist assistant",
            "athletic trainer",
            "occupational therapist",
            "medical receptionist",
            "therapy aide",
        },
        role_families={"healthcare", "operations"},
        industries={"healthcare"},
        fallback_priority=8,
    ),
    _source(
        "InformaGroupPlc",
        "Informa",
        {
            "journalism",
            "journalist",
            "editor",
            "writer",
            "copywriter",
            "publishing",
            "communications",
            "public relations",
            "marketing",
            "content",
            "research",
            "events",
            "sales",
            "finance",
        },
        role_families={"marketing", "design", "operations", "finance", "data"},
        industries={"media", "education", "entertainment"},
        fallback_priority=8,
    ),
    _source(
        "NBCUniversal3",
        "NBCUniversal",
        {
            "journalism",
            "journalist",
            "reporter",
            "editor",
            "writer",
            "communications",
            "marketing",
            "media",
            "production",
            "film",
            "television",
            "designer",
            "creative",
        },
        role_families={"marketing", "design", "operations", "data"},
        industries={"media", "entertainment"},
        fallback_priority=9,
    ),
    _source(
        "SynchronyGroup",
        "Synchrony Group",
        {
            "medical writer",
            "scientific writer",
            "medical communications",
            "clinical",
            "scientific",
            "writer",
            "editor",
            "creative",
            "marketing",
        },
        role_families={"marketing", "design", "healthcare"},
        industries={"healthcare", "media"},
        fallback_priority=5,
    ),
    _source(
        "Evolution",
        "Evolution",
        {
            "accountant",
            "accounting",
            "finance",
            "human resources",
            "recruiter",
            "customer service",
            "operations",
            "marketing",
            "studio",
            "hospitality",
            "game presenter",
        },
        role_families={"finance", "operations", "marketing"},
        industries={"entertainment", "hospitality", "financial_services"},
        fallback_priority=6,
    ),
    _source(
        "PublicStorage",
        "Public Storage",
        {
            "property manager",
            "real estate",
            "customer service",
            "call center",
            "maintenance",
            "facilities",
            "retail",
            "district manager",
        },
        role_families={"operations", "finance", "marketing"},
        industries={"real_estate", "retail"},
        fallback_priority=6,
    ),
    _source(
        "Experian",
        "Experian",
        {
            "finance",
            "financial analyst",
            "accountant",
            "data analyst",
            "analytics",
            "business analyst",
            "marketing",
            "sales",
            "software engineer",
            "cybersecurity",
            "human resources",
            "recruiter",
        },
        role_families={
            "finance",
            "data",
            "software",
            "cybersecurity",
            "marketing",
            "operations",
        },
        industries={"financial_services", "technology"},
        fallback_priority=7,
    ),
    _source(
        "CityAndCountyOfSanFrancisco1",
        "City and County of San Francisco",
        {
            "government",
            "public service",
            "policy analyst",
            "social worker",
            "librarian",
            "library",
            "public health",
            "engineer",
            "electrician",
            "mechanic",
            "operator",
            "accountant",
            "administrative assistant",
        },
        role_families={"policy", "operations", "healthcare", "finance", "data", "software"},
        industries={"government", "public_interest", "public_policy"},
        location_terms={"san francisco", "sf", "oakland", "berkeley", "california", "ca"},
        fallback_priority=4,
    ),
)
